openapi: 3.0.3
info:
  title: Bright Sample Api
  description: Bright Sample Api
  version: 1.0.0
servers:
  - description: Localhost
    url: http://localhost:8080
paths:
  /blogs-v2:
    get:
      operationId: blog-posts-get
      description: Get list of blog posts
      parameters:
        - $ref: '#/components/parameters/Page'
      responses:
        200:
          description: List of blog posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlogPage'
    post:
      operationId: blog-posts-create
      description: Create a blog post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogPost'
            example:
              id: 123
              content: Super content
              publishedAt: 2022-03-04
      responses:
        200:
          description: A location of blog post
          headers:
            Location:
              description: Location of blog post

components:
  schemas:
    BlogPost:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        publishedAt:
          type: string
          format: date
    BlogPage:
      description: A list of blog posts
      type: array
      items:
        $ref: '#/components/schemas/BlogPost'

  parameters:
    Page:
      description: Pagination parameters
      name: page
      in: query
      schema:
        type: integer
